# Generated by Django 5.1.6 on 2025-03-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_starredvacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='starredvacancy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='starredvacancy',
            name='vacancy',
        ),
        migrations.DeleteModel(
            name='FavoriteJob',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='StarredVacancy',
        ),
    ]
