# Generated by Django 5.1.6 on 2025-03-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_jobapplication_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
