# Generated by Django 5.1.6 on 2025-03-25 18:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default=datetime.date(2025, 3, 25), max_length=50),
            preserve_default=False,
        ),
    ]
