# Generated by Django 5.1.6 on 2025-03-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_employerprofile_logo_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(default='example@example.com', upload_to='logos/'),
            preserve_default=False,
        ),
    ]
