# Generated by Django 5.1.6 on 2025-03-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_vacancy_created_at_remove_vacancy_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
